# Generated by Django 3.0.3 on 2020-04-23 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('answer', models.CharField(max_length=10)),
                ('expire_time', models.DateTimeField(default=datetime.datetime(2020, 4, 23, 10, 41, 27, 940622))),
            ],
        ),
    ]
