# Generated by Django 3.0.3 on 2020-05-14 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchastore',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 10, 52, 57, 586691, tzinfo=utc)),
        ),
    ]
