# Generated by Django 3.0.7 on 2020-06-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchastore',
            name='expire_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
