# Generated by Django 3.0.3 on 2020-05-29 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0002_auto_20200514_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchastore',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 12, 54, 48, 646281, tzinfo=utc)),
        ),
    ]
