# Generated by Django 3.1.3 on 2020-11-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='list_column',
            field=models.IntegerField(default=20),
        ),
    ]
