# Generated by Django 3.1.3 on 2020-11-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201121_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nav_color',
            field=models.TextField(default='#545c64'),
        ),
    ]
