# Generated by Django 3.1rc1 on 2020-07-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200717_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_judger',
            field=models.BooleanField(default=False),
        ),
    ]
