# Generated by Django 3.1.5 on 2021-02-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210203_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
