# Generated by Django 3.1 on 2020-08-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='list_column',
            field=models.IntegerField(default=50),
        ),
    ]
