# Generated by Django 4.1.2 on 2022-10-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210416_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ac_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
