# Generated by Django 3.1 on 2020-08-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_list_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='editor_theme',
            field=models.IntegerField(default=0),
        ),
    ]
