# Generated by Django 4.1.2 on 2022-10-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_ac_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ac_heatmap',
            field=models.TextField(default='\\{\\}'),
        ),
        migrations.AddField(
            model_name='account',
            name='submit_heatmap',
            field=models.TextField(default='\\{\\}'),
        ),
        migrations.AddField(
            model_name='account',
            name='submit_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='account',
            name='ac_list',
            field=models.TextField(default='[]'),
        ),
    ]
