# Generated by Django 4.1.2 on 2022-10-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_account_ac_heatmap_account_submit_heatmap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ac_heatmap',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='account',
            name='submit_heatmap',
            field=models.TextField(default='{}'),
        ),
    ]
