# Generated by Django 3.0.3 on 2020-02-20 08:54

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import soj.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(storage=soj.storage.AvatarStorage(builtins.id), upload_to='avatar')),
                ('solved', models.IntegerField(default=0)),
                ('submit_time', models.IntegerField(default=0)),
                ('to_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
