# Generated by Django 3.0.3 on 2020-03-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soj', '0003_auto_20200305_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='home',
            field=models.TextField(default='# Hello World!'),
        ),
    ]
