JUDGE_LANGUAGE_CPP      = 0     # C++ (compiler: g++)
JUDGE_LANGUAGE_CPP11    = 1     # C++11 (compiler: g++)
JUDGE_LANGUAGE_CPP14    = 2     # C++14 (compiler: g++)
JUDGE_LANGUAGE_CPP17    = 3     # C++17 (compiler: g++)
JUDGE_LANGUAGE_CPP20    = 4     # C++20 (compiler: g++)
JUDGE_LANGUAGE_C        = 5     # C (compiler: gcc)
JUDGE_LANGUAGE_CSHARP   = 6     # C#
JUDGE_LANGUAGE_CLANG    = 7     # C++ (compiler: clang++)
JUDGE_LANGUAGE_CLANG11  = 8     # C++11 (compiler: clang++)
JUDGE_LANGUAGE_CLANG14  = 9     # C++14 (compiler: clang++)
JUDGE_LANGUAGE_CLANG17  = 10    # C++17 (compiler: clang++)
JUDGE_LANGUAGE_CLANG20  = 11    # C++20 (compiler: clang++)
JUDGE_LANGUAGE_RUST     = 12    # Rust-lang
JUDGE_LANGUAGE_PYTHON2  = 13    # Python 2
JUDGE_LANGUAGE_PYTHON3  = 14    # Python 3
JUDGE_LANGUAGE_PASCAL   = 15    # Free Pascal
JUDGE_LANGUAGE_GOLANG   = 16    # Go-lang
JUDGE_LANGUAGE_RUBY     = 17    # Ruby
JUDGE_LANGUAGE_JAVA     = 18    # Java