# Generated by Django 3.0.2 on 2020-01-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='background',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sampleinput',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sampleoutput',
            field=models.TextField(null=True),
        ),
    ]
