# Generated by Django 3.0.2 on 2020-01-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20200128_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sampleinput',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sampleoutput',
            field=models.TextField(blank=True, null=True),
        ),
    ]
