# Generated by Django 3.0.2 on 2020-02-04 10:03

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20200128_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='background',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sampleinput',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sampleoutput',
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
