# Generated by Django 3.0.2 on 2020-02-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20200128_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='background',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sampleinput',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sampleoutput',
        ),
        migrations.AddField(
            model_name='problem',
            name='allow_html',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='show_id',
            field=models.IntegerField(unique=True),
        ),
    ]
