# Generated by Django 3.0.3 on 2020-02-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20200212_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'permissions': (('view_hidden', 'Can view hidden problems.'),)},
        ),
    ]
