# Generated by Django 3.0.7 on 2020-06-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_auto_20200618_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': (('edit', 'Can edit tag'), ('remove', 'Can remove tag'))},
        ),
    ]
