# Generated by Django 3.0.7 on 2020-06-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_auto_20200619_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'permissions': (('view_hidden', 'Can view hidden problem'),)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
