# Generated by Django 3.1.5 on 2021-02-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0013_auto_20200728_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='testdata_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['pid'], name='problem_pro_pid_376afa_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['title'], name='problem_pro_title_e83459_idx'),
        ),
    ]
