# Generated by Django 3.1.6 on 2021-02-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_auto_20210204_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='testdata_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
