# Generated by Django 4.1.2 on 2022-11-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_problem_testdata_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status_cnt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='submit_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
