# Generated by Django 3.0.7 on 2020-07-17 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='judge_detail',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='status.StatusDetail'),
        ),
    ]
