# Generated by Django 3.0.7 on 2020-07-17 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0012_auto_20200716_1903'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0003_auto_20200717_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='judge_detail',
        ),
        migrations.AddField(
            model_name='statusdetail',
            name='main_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='judge_detail', to='status.Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
