# Generated by Django 3.1b1 on 2020-07-18 01:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0012_auto_20200716_1903'),
        ('status', '0004_auto_20200717_1428'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='status',
            index_together={('owner', 'problem')},
        ),
    ]
