# Generated by Django 3.1b1 on 2020-07-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20200718_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
