# Generated by Django 3.1rc1 on 2020-07-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_auto_20200724_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusdetail',
            name='answer_s',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='statusdetail',
            name='error_s',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='statusdetail',
            name='input_s',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='statusdetail',
            name='output_s',
            field=models.CharField(default='', max_length=100),
        ),
    ]
