# Generated by Django 3.1rc1 on 2020-07-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0009_auto_20200724_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusdetail',
            old_name='main_state',
            new_name='main_status',
        ),
    ]
