# Generated by Django 3.1.5 on 2021-02-03 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0010_auto_20200724_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusdetail',
            name='main_status',
        ),
        migrations.AddField(
            model_name='status',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='judge_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='judged_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='judge_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='lang_info',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='lang',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='status',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['state'], name='status_stat_state_1c8f49_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['score'], name='status_stat_score_8b89ef_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['lang'], name='status_stat_lang_670401_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['problem', 'owner'], name='status_stat_problem_fb6445_idx'),
        ),
        migrations.DeleteModel(
            name='StatusDetail',
        ),
    ]
